config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest', to: 'guest_sessions#create'

  resources :users do
    member do
      get :following
      get :followers
      get :favorite
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :best_photos, only: %i[create destroy]

  resources :posts do
    resource :likes, only: %i[create destroy]
    resource :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    collection do
      get :timeline
      get :popular
      get :index
      get :feature
    end
  end

  resource :comment_likes, only: %i[create destroy]

  resources :contests
  resources :contest_posts, only: %i[new create index show] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :notifications, only: :index
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @user = User.find_by(id: current_user.id)
      @timeline_posts = current_user.timeline.page(params[:page])
      @timeline_posts = @timeline_posts.includes(:user)
      @posts = Post.page(params[:page])
      @posts = @posts.includes(:user)
      redirect_to timeline_posts_path
    else
      @posts = Post.page(params[:page])
      @posts = @posts.includes(:user)

    end
  end

  def about; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "TONE") %>

<% if logged_in? %>
  <div class="container pt-4">
    <% if !@timeline_posts.nil? %>
      <%= render "posts/index_timeline", { posts: @timeline_posts, user: @user } %>
    <% else %>
      <div class="no-contents d-flex flex-column align-items-center justify-content-center mx-auto">
        <div class="no-contents-title font-weight-bold">投稿がありません</div>
        <%= render "posts/index_posts", posts: @posts %>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="about-image d-flex flex-column align-items-center justify-content-center mx-auto">
    <div class="title-box">
      <p class="apptitle pt-4">Tone</p>
      <p class="title-message">モノクロで自由に</p>
    </div>
    <div class="top-login">
      <span><%= link_to "新規登録", signup_path, class:"btn btn-success mr-2" %></span>
      <span><%= link_to "ログイン", login_path, class:"btn btn-primary" %></span>
      <p class="text-center"><%= link_to "ゲストログイン", guest_path, method: :post, class:"btn btn-warning mt-2" %></p>
    </div>
  </div>
<% end %>