config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest', to: 'guest_sessions#create'

  resources :users do
    member do
      get :following
      get :followers
      get :favorite
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :best_photos, only: %i[create destroy]

  resources :posts do
    resource :likes, only: %i[create destroy]
    resource :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    collection do
      get :timeline
      get :popular
      get :index
      get :feature
    end
  end

  resource :comment_likes, only: %i[create destroy]

  resources :contests
  resources :contest_posts, only: %i[new create index show] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :notifications, only: :index
end

app/models/contest.rb
# == Schema Information
#
# Table name: contests
#
#  id                 :integer          not null, primary key
#  condition          :text
#  gold_explanation   :string
#  gold_prize         :string
#  gold_title         :string
#  image              :string
#  main               :text
#  period             :string
#  silver_explanation :string
#  silver_prize       :string
#  silver_title       :string
#  title              :string
#  win_a_prize        :string
#  win_explanation    :string
#  win_title          :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :integer
#
class Contest < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader
  mount_uploader :gold_prize, ImageUploader
  mount_uploader :silver_prize, ImageUploader
  mount_uploader :win_a_prize, ImageUploader

  validates :user_id, presence: true
  validates :image, presence: true
  validates :main, presence: true
  validates :title, presence: true
  validates :condition, presence: true
  validate :image_size

  private

  # アップロードされた画像のサイズをバリデーションする
  def image_size
    errors.add(:image, '15MBまでの画像を投稿してください') if image.size > 15.megabytes
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :logged_in_user, only: %i[create destroy]
  before_action :correct_user, only: :destroy

  def index
    @contests = Contest.page(params[:page])
  end

  def new
    @contest = Contest.new
  end

  def create
    @contest = current_user.contests.build(contest_params)
    if @contest.save
      redirect_to @contest
    else
      redirect_to new_contest_path
    end
  end

  def show
    @contest = Contest.find(params[:id])
  end

  def edit
    @contest = Contest.find(params[:id])
  end

  def update
    @contest = Contest.find(params[:id])
    if @contest.update_attributes(contest_params)
      redirect_to @contest
    else
      render 'edit'
    end
  end

  def destroy
    @contest.destroy
    flash[:success] = 'コンテストを削除しました'
    redirect_to contests_path
  end

  private

  def contest_params
    params.require(:contest).permit(:title, :main, :condition, :period, :image,
                                    :gold_prize, :gold_title, :gold_explanation,
                                    :silver_prize, :silver_title, :silver_explanation,
                                    :win_a_prize, :win_title, :win_explanation)
  end

  def correct_user
    @contest = current_user.contests.find_by(id: params[:id])
    redirect_to root_url if @contest.nil?
  end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_contest_form.html.erb
<%= render "shared/error" %>
<div class="body">
  <div class="row mt-5">
    <div class="col-md-6 mx-auto offset-3">
    <h2>コンテスト作成</h2>
    
      <%= form_with model: contest do |f| %>
        <%= f.label :title, "コンテスト名" %>
        <%= f.text_field :title, class: "form-control" %>  
        
        <%= f.label :main, "コンテスト内容" %>
        <%= f.text_area :main, class: "form-control", rows: 12 %>
        
        <%= f.label :condition, "応募要項" %>
        <%= f.text_area :condition, class: "form-control", rows: 12 %>

        <%= f.label :period, "応募期間" %>
        <%= f.text_field :period, class: "form-control" %>

        <%= f.label :image, "コンテストページの写真をアップロードしてください" %>
        <%= f.file_field :image, accept: "image/jpg,image/jpeg,image/gif,image/png" %>

        <h3 class="mt-5">コンテスト結果 (応募期間終了後に入力)</h3>

        <h4 class="mt-4"><金賞></h4>
        <%= f.label :gold_title, "金賞タイトル" %>
        <%= f.text_field :gold_title, class: "form-control" %> 

        <%= f.label :gold_explanation, "金賞の説明" %>
        <%= f.text_area :gold_explanation, class: "form-control", rows: 5 %> 

        <%= f.label :gold_prize, "金賞写真" %>
        <%= f.file_field :gold_prize, accept: "image/jpg,image/jpeg,image/gif,image/png", class: "image" %> 

        <h4 class="mt-4"><銀賞></h4>
        <%= f.label :silver_title, "銀賞タイトル" %>
        <%= f.text_field :silver_title, class: "form-control" %> 

        <%= f.label :silver_explanation, "銀賞の説明" %>
        <%= f.text_area :silver_explanation, class: "form-control", rows: 5 %> 

        <%= f.label :silver_prize, "銀賞写真" %>
        <%= f.file_field :silver_prize, accept: "image/jpg,image/jpeg,image/gif,image/png", class: "image" %> 

        <h4 class="mt-4"><入賞></h4>
        <%= f.label :win_title, "入賞タイトル" %>
        <%= f.text_field :win_title, class: "form-control" %> 

        <%= f.label :win_explanation, "入賞の説明" %>
        <%= f.text_area :win_explanation, class: "form-control", rows: 5 %> 

        <%= f.label :win_a_prize, "入賞写真" %>
        <%= f.file_field :win_a_prize, accept: "image/jpg,image/jpeg,image/gif,image/png", class: "image" %> 

        <div class="justify-content-center col-lg-4 col-md-6 mx-auto mt-3 mb-3">
          <%= f.submit "保存する", class: "btn btn-primary mt-4 mb-5" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contests/edit.html.erb
<% provide(:title, "コンテスト編集") %>

<%= render "contest_form", contest: @contest %>

app/views/contests/index.html.erb
<% provide(:title, "コンテスト一覧") %>
<div class="container pt-4">
  <h2 class="text-center mt-4 mb-3">コンテスト一覧</h2>
  <div class="row post-cards">
    <% @contests.each do |contest| %>
      <div class="col-lg-6 col-md-12 card-index">
        <div class="card bg-white">
          <div class="card-header contest-header">
            <div class="contest-title text-center">
              <%= contest.title %>
            </div>
          </div>
          <img class="card-img-top">
            <%= link_to image_tag(contest.image.url.to_s, class: "contest_image img-fluid", alt: "contest image"), contest %>
          </img>
          <div class="card-footer text-right contest-footer">
            <span>応募期間：<%= contest.period %></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= paginate @contests %> 

app/views/contests/new.html.erb
<% provide(:title, "コンテスト作成") %>

<%= render "contest_form", contest: @contest %>

app/views/contests/show.html.erb
<% provide :title, "コンテスト" %>

<div class="container mt-3 pb-3">
  <%= image_tag(@contest.image.head.url, class: "img-fluid", alt: "image") %>
  <div class="row">
    <div class="col-md-8 mx-auto">
      <div class="text-center mt-4">
        <h2><%= @contest.title %></h2>
      </div>

      <% if @contest.gold_prize? && @contest.silver_prize? && @contest.win_a_prize? %>
        <h2 class="text-center mt-5">＜結果発表＞</h2>

        <h2 class="text-center mt-5">金賞</h2>
        <div class="photo-title text-center mt-4 mb-3">
          <%= @contest.gold_title %>
        </div>
        <%= image_tag(@contest.gold_prize.url, class: "img-fluid", alt: "image") %>
        <div class="photo-explanation mt-3">
          <%= simple_format(@contest.gold_explanation) %>
        </div>

        <h3 class="text-center mt-5">銀賞</h3>
        <div class="photo-title text-center mt-4 mb-3">
          <%= @contest.silver_title %>
        </div>
        <%= image_tag(@contest.silver_prize.url, class: "img-fluid", alt: "image") %>
        <div class="photo-explanation mt-3">
          <%= simple_format(@contest.silver_explanation) %>
        </div>

        <h4 class="text-center mt-5">入賞</h4>
        <div class="photo-title text-center mt-4 mb-3">
          <%= @contest.win_title %>
        </div>
        <%= image_tag(@contest.win_a_prize.url, class: "img-fluid", alt: "image") %>
        <div class="photo-explanation mt-3">
          <%= simple_format(@contest.win_explanation) %>
        </div>

      <% else %>
        <div class="contest-main mt-5">
          <%= safe_join(@contest.main.split("\n"),tag(:br)) %>
        </div>
        <h2 class="text-center mt-5">応募要項</h2>
        <div class="contest-condition mt-4 mb-5">
          <%= safe_join(@contest.condition.split("\n"),tag(:br)) %>
        </div>
        <div class="text-center pt-4 mb-5">
        <%= link_to "コンテストに投稿する", new_contest_post_path, class: "btn btn-lg btn-dark text-white" %>
        </div>
      <% end %>

      <% if logged_in? && current_user.admin? %>
        <div class="text-center pt-4 mb-5">
          <%= link_to "投稿写真一覧", contest_posts_path, class: "btn btn-outline-dark" %>
          <%= link_to "編集", edit_contest_path(@contest.id), class: "btn btn-outline-dark" %>
          <%= link_to "削除", @contest, method: :delete, data: { confirm: "削除しますか?" }, class: "btn btn-outline-dark" %>
        </div>
      <% end %>
    </div>
  </div>
</div>