config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest', to: 'guest_sessions#create'

  resources :users do
    member do
      get :following
      get :followers
      get :favorite
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :best_photos, only: %i[create destroy]

  resources :posts do
    resource :likes, only: %i[create destroy]
    resource :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    collection do
      get :timeline
      get :popular
      get :index
      get :feature
    end
  end

  resource :comment_likes, only: %i[create destroy]

  resources :contests
  resources :contest_posts, only: %i[new create index show] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :notifications, only: :index
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :integer          not null, primary key
#  action     :string           default(""), not null
#  checked    :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  comment_id :integer
#  post_id    :integer
#  visited_id :integer          not null
#  visitor_id :integer          not null
#
# Indexes
#
#  index_notifications_on_comment_id  (comment_id)
#  index_notifications_on_post_id     (post_id)
#  index_notifications_on_visited_id  (visited_id)
#  index_notifications_on_visitor_id  (visitor_id)
#
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="low">
  <div class="col-md-6 mx-auto text-center">
   
    <div class="form-inline">
      <span class="mt-4 mx-auto">
        <%= link_to user_path(visitor) do %>
          <%= visitor.name %>
          <%= 'さんが' %>
        <% end %>

        <% if notification.action == 'follow' %>
          <%= "あなたをフォローしました" %>
        <% elsif notification.action == 'like' %>
          <%= link_to 'あなたの投稿', notification.post, style: "font-weight: bold;" %>
          <%= "にいいねしました" %>
        <% elsif notification.action == 'comment' %>
          <% if notification.post.user_id == visited.id %>
            <%= link_to "あなたの投稿", notification.post, style: "font-weight: bold;" %>
            <%= "にコメントしました" %>
          <% else %>
            <span>
              <%= link_to post_path(notification.post) do %>
                <strong>
                  <%= notification.post.user.name + 'さんの投稿' %>
                </strong>
              <% end %>
            </span>
            <%= "にコメントしました" %>
            <P class="text-muted mb-0">
              <%= Comment.find_by(id: notification.comment_id)&.comment %>
            </p>
          <% end %>
        <% end %>

        <div class="small text-muted text-right">
          <%= time_ago_in_words(notification.created_at).upcase %>
        </div>
      </span>
    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<% provide :title, "通知一覧" %>

<div class="col-md-6 mx-auto text-center">
  <h4 class="border-bottom border-secondary mt-5">通知一覧</h4>
</div>

<% notifications = @notifications.where.not(visitor_id: current_user.id) %>

<% if notifications.exists? %>
  <%= render notifications %>
  <%= paginate notifications %>
<% else %>
  <p class="text-center mt-3">通知はありません</p>
<% end %>