config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest', to: 'guest_sessions#create'

  resources :users do
    member do
      get :following
      get :followers
      get :favorite
    end
  end

  resources :relationships, only: %i[create destroy]
  resources :best_photos, only: %i[create destroy]

  resources :posts do
    resource :likes, only: %i[create destroy]
    resource :comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
    collection do
      get :timeline
      get :popular
      get :index
      get :feature
    end
  end

  resource :comment_likes, only: %i[create destroy]

  resources :contests
  resources :contest_posts, only: %i[new create index show] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :notifications, only: :index
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  admin           :boolean          default(FALSE)
#  avatar          :string
#  email           :string
#  name            :string
#  password_digest :string
#  profile         :text
#  remember_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :comment_likes
  has_many :comment_post, through: :comment_likes, source: :post

  has_many :contests, dependent: :destroy
  has_many :contest_posts

  has_many :active_notifications, class_name: 'Notification',
                                  foreign_key: 'visitor_id',
                                  dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification',
                                   foreign_key: 'visited_id',
                                   dependent: :destroy

  # 仮想の属性（トークンをデータベースに保存せずに実装するため）
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 10 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
  validates :profile, length: { maximum: 150 }

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # フォローしているか確認する
  def following?(user)
    active_relationships.find_by(followed_id: user.id)
  end

  # フォローする
  def follow(user)
    active_relationships.create!(followed_id: user.id)
  end

  # フォローを外す
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # いいねしているか確認する
  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  # お気に入りの投稿として保存しているか確認する
  def already_made_favorite?(post)
    favorites.exists?(post_id: post.id)
  end

  # 表示している投稿がベストフォトとして保存されているか確認する
  def saved_this_best?(post)
    best_photos.exists?(user_id: id, post_id: post.id)
  end

  # コメントにいいねしているか確認する
  def comment_liked?(comment)
    comment_likes.exists?(comment_id: comment.id)
  end

  # ユーザーのフィードを返す
  def timeline
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # フォロー通知の作成
  def create_notification_follow(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update destroy following followers]
  before_action :correct_user, only: %i[edit update]
  before_action :admin_user, only: %i[index destroy]

  def index
    @users = User.order(admin: :DESC, id: :ASC).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
    @followings = @user.following
    @followers = @user.followers
    @favorites = @user.favorite_posts.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "#{@user.name}さん、Toneへようこそ！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_update_params)
      flash[:success] = 'プロフィールの編集が完了しました'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'ユーザーを削除しました'
    redirect_to users_url
  end

  def following
    @title = 'Following'
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page])
    render 'show_follow'
  end

  def favorite
    @favorites = current_user.favorite_posts.page(params[:page])
    render 'show_favorite'
  end

  private

  # ストロングパラメータ
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_update_params
    params.require(:user).permit(:name, :email, :avatar, :profile)
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # 管理者かどうかを確認
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path,
             method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :user_id, @user.id %>
  <%= f.submit "フォロー", class: "btn btn-secondary btn-follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<div class="follow_form_<%= user.id %>">
  <% unless current_user?(user) %>
    <div id="follow_form">
      <% if current_user.following?(user) %>
        <%= render 'unfollow', user: user %>
      <% else %>
        <%= render 'follow', user: user %>
      <% end %>
    </div>
  <% end %> 
</div> 

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name, 'ユーザー名（10文字以内）' %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'name', required: 'required' %>

  <%= f.label :email, 'メールアドレス' %>
  <%= f.email_field :email, class: 'form-control', autocomplete: 'email', required: 'required' %>

  <%= f.label :password, 'パスワード（6文字以上）' %>
  <%= f.password_field :password, class: 'form-control', autocomplete: 'password', required: 'required' %>

  <%= f.label :password_confirmation, "確認用パスワード" %>
  <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: 'password', required: 'required' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

<% if !logged_in? %>
  <%= link_to "ログイン", login_path %>
<% end %>

app/views/users/_post.html.erb
<li id="post-<%= post.id %>">
  <% if @user.avatar? %>
    <%= image_tag(@user.avatar.url, size: "50", class: "avatar_present_img rounded-circle z-depth-0 avatar-image", alt: "avatar image") %>
  <% else %>
    <%= image_tag("no-avatar.png", size: "50", class: "avatar_present_img rounded-circle z-depth-0 avatar-image", alt: "avatar image") %>
  <% end %>      
  
  <span class="image">
    <%= link_to image_tag(post.image.url), post if post.image? %>
  </span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user?(post.user) %>
      <%= link_to "投稿を削除", post, method: :delete,
                                    data: { confirm: "削除しますか?" } %>
    <% end %>
  </span>
</li> 

app/views/users/_show_favorites.html.erb
<div class="row">
  <% favorites.each do |post| %>
    <div class="col-lg-4 col-md-6 card-index">
      <div class="card PhotoBox">
        <%= link_to image_tag(post.image.thumb.url.to_s, class: 'post_image_index img-fluid', alt: 'post image'), post %>
        <div class="SlideBox">
          <span class="mr-2">いいね<%= post.likes.count %></span>
          <span>コメント<%= post.comments.count %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $(document).on("turbolinks:load", function() {
    $(".PhotoBox").hover(function(){
      $(".SlideBox",this).stop().animate({bottom:"0px"},"fast");
    },function(){
      $(".SlideBox",this).stop().animate({bottom:"-70px"},"slow");
    });
  })
</script>

app/views/users/_show_follows.html.erb
<div class="row">
  <% objects.each do |user| %>
    <div class="col-lg-4 col-md-6 col-sm-6">
      <div class="user-card card card-index2 align-items-center">
        <% if user.avatar? %>
          <%= link_to image_tag(user.avatar.to_s, size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% else %>
          <%= link_to image_tag("no-avatar.png", size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
        <% end %>
        <%= link_to user.name, user, class: 'user-name pt-3' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_show_posts.html.erb
<div class="row">
  <% posts.each do |post| %>
    <div class="col-lg-4 col-md-6 card-index">
      <div class="card PhotoBox">
        <%= link_to image_tag(post.image.thumb.url.to_s, class: 'post_image_index img-fluid', alt: 'post image'), post %>
        <div class="SlideBox">
          <span class="mr-2">いいね<%= post.likes.count %></span>
          <span>コメント<%= post.comments.count %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $(document).on("turbolinks:load", function() {
    $(".PhotoBox").hover(function(){
      $(".SlideBox",this).stop().animate({bottom:"0px"},"fast");
    },function(){
      $(".SlideBox",this).stop().animate({bottom:"-70px"},"slow");
    });
  })
</script>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(user),
             method: :delete, remote: true) do |f| %>
  <%= hidden_field_tag :user_id, user.id %>
  <%= f.submit "フォロー中", class: "btn btn-secondary btn-follow" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <div class="user_info">
    <% if user.avatar? %>
      <%= image_tag(user.avatar.url, size: 50, class: 'avatar_present_img rounded-circle z-depth-0 avatar-image', alt: 'avatar image') %>
    <% else %>
      <%= image_tag("no-avatar.png", size: 50, class: "avatar_present_img rounded-circle z-depth-0 avatar-image", alt: "avatar image") %>
    <% end %>    
  </div>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "削除", user, method: :delete,
                    data: {confirm: "本当に削除してよいですか？"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー情報の編集") %>

<div class="col-md-6 col-md-offset-3 mx-auto">
  <%= render 'shared/error' %>

  <h2 class="form_title mt-3 mb-4">プロフィールの編集</h2>

  <%= form_with model: @user, local: true do |f| %>
    <div class="text-center mb-3"> 
      <% if @user.avatar? %>
        <%= f.label :avatar, class: "form-image" do %>
          <%= image_tag(@user.avatar.url, size: "200", class: "avatar_present_img rounded-circle z-depth-0 avatar-image", alt: "avatar image") %>
          <%= f.file_field :avatar %>
        <% end %>
      <% else %>
        <%= f.label :avatar, class: "form-image" do %>
          <%= image_tag("no-avatar.png", size: "200", class: "avatar_present_img rounded-circle z-depth-0 avatar-image", alt: "avatar image") %>
          <%= f.file_field :avatar %>
        <% end %>
      <% end %>
    </div>
        
    <%= f.label :name, 'ユーザー名（20文字以内）' %>
    <%= f.text_field :name, class: 'form-control', autocomplete: 'name', required: 'required' %>  
    
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, class: 'form-control', autocomplete: 'email', required: 'required' %>

    <%= f.label :profile, "自己紹介（150文字以内）" %>
    <%= f.text_area :profile, class: 'form-control', rows: 5 %>
    
    <div class="text-right">
      <%= link_to '戻る', user_path(current_user), class: "btn btn-outline-dark mb-2" %>
      <%= f.submit "変更を保存する", class: "btn btn-dark mb-5" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide :title, 'すべてのユーザー' %>
<%= render "shared/success_messages" %>

<% if @users.any? %>

  <div class="container">
    <h2 class="text-center font-weight-bold mt-4 mb-3">すべてのユーザー</h2>
    <div class="row">
      <% @users.each do |user| %>
        <div class="col-lg-4 col-md-6 col-sm-6 card-index">
          <div class="card align-items-center">
            <% if user.avatar? %>
              <%= link_to image_tag(user.avatar.to_s, size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
            <% else %>
              <%= link_to image_tag("no-avatar.png", size: "150x150", class: "rounded-circle", alt: "avatar image"), user %>
            <% end %>
            <%= link_to user.name, user, class: 'user-name' %>

            <% if current_user.admin? && !(user.admin?) %>
              <%= link_to 'このユーザーを削除する', user, method: :delete, data: { confirm: 'このユーザーを削除しますか？' }, class:'btn btn-dark' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <%= paginate @users %>

  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>

<div class="login-image">
  <div class="container user-form">
    <h2 class="pb-3 text-center text-white">新規ユーザー登録</h2> 
    
      <%= form_with model: @user, local: true do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <div class="text-white pt-3">
          <%= f.label :name, "ユーザー名（10文字以内）" %>
          <%= f.text_field :name, class: "form-control", autocomplete: "name", required: "required" %>  
        </div>

        <div class="text-white pt-2">
          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email, class: 'form-control', autocomplete: 'email', required: 'required' %>
        </div>

        <div class="text-white pt-2">
          <%= f.label :password, "パスワード（8文字以上）" %>
          <%= f.password_field :password, class: 'form-control', autocomplete: 'password', required: 'required' %>
        </div>

        <div class="text-white pt-2">
          <%= f.label :password_confirmation, "確認用パスワード" %>
          <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: 'password', required: 'required' %>
        </div>

        <div class="login-btn pt-3">
          <%= f.submit "ユーザー登録", class: "btn btn-primary" %>
        </div>
      <% end %>

      <p><%= link_to "ログイン", login_path, class:"btn btn-success" %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'マイページ') %>

<div class="container mt-5">
  <div class="row mx-auto page-top" style="max-width: 700px;">
    <div class="col-md-5">
      <div class="user-avator">
        <% if @user.avatar? %>
          <%= image_tag(@user.avatar.url, size: '180x180', class: 'rounded-circle img-fluid avatar-image', alt: 'avatar image') %>
        <% else %>
          <%= image_tag('no-avatar.png', size: '180x180', class: 'rounded-circle img-fluid avatar-image', alt: 'avatar image') %>
        <% end %>    
      </div>
    </div>
    <div class="d-flex flex-column mt-3 col-md-7">
      <div class="user-name">
        <%= @user.name %>
      </div>
      <div class="user-menu mt-3">
        <% if logged_in? %>
          <% if current_user.admin? %>
            <% if @user.admin? %>
              <!-- なにも表示しない -->
            <% else %>
              <%= link_to 'このユーザーを削除する', @user, method: :delete, data: { confirm: 'このユーザーを削除しますか？' }, class:'btn btn-outline-dark' %>
            <% end %>
          <% else %>
            <% if current_user.id == @user.id %>
              <% if guest_user %>
                <!-- なにも表示しない -->
              <% else %>
                <%= link_to 'プロフィール編集', edit_user_path(current_user), class:'btn btn-outline-dark' %>
              <% end %>
            <% else %>
              <%= render 'follow_form', user: @user %>
            <% end %>
          <% end %>
          <div class="user-status mt-3">
            <span class="status-name">投稿</span>
            <span class="status-value mr-4"><%= @user.posts.count.to_s(:delimited) %></span>

            <span class="status-name">フォロワー</span>
            <span class="status-value mr-4" id="followers_<%= @user.id %>">
              <%= @user.followers.count.to_s(:delimited) %>
            </span>

            <span class="status-name">フォロー</span>
            <span class="status-value" id="following_<%= @user.id %>">
              <%= @user.following.count.to_s(:delimited) %>
            </span>

          </div>
          <div class="user-profile mt-3" style="max-width: 400px; max-height: 140px; overflow: hidden;">
            <%= simple_format(@user.profile) %>
          </div>
        <% end %>
      </div>
    </div> 
  </div>

  <ul class="nav nav-tabs justify-content-center mt-5">
    <li class="nav-item">
      <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#item1" role="tab" aria-controls="item1" aria-selected="true">
        <div class="user-status">
          <span class="status-name">投稿</span>
        </div>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="followings-tab" data-toggle="tab" href="#item2" role="tab" aria-controls="item2" aria-selected="true">
        <div class="user-status">
          <span class="status-name">フォロー</span>
        </div>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="followers-tab" data-toggle="tab" href="#item3" role="tab" aria-controls="item3" aria-selected="true">
        <div class="user-status">
          <span class="status-name">フォロワー</span>
        </div>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="favorites-tab" data-toggle="tab" href="#item4" role="tab" aria-controls="item4" aria-selected="true">
        <div class="user-status">
          <span class="status-name">お気に入り</span>
        </div>
      </a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane fade show active" id="item1" role="tabpanel" aria-labelledby="posts-tab">
      <% if @user.posts.any? %>
        <%= render "show_posts", posts: @posts %>
      <% else %>
        <div class="no-contents d-flex justify-content-center align-items-center">
          投稿がありません
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="item2" role="tabpanel" aria-labelledby="followings-tab">
      <% if @user.following.any? %>
        <%= render "show_follows", objects: @followings %>
      <% else %>
        <div class="no-contents d-flex justify-content-center align-items-center">
          誰もフォローしていません
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="item3" role="tabpanel" aria-labelledby="followers-tab">
      <% if @user.followers.any? %>
        <%= render "show_follows", objects: @followers %>
      <% else %>
        <div class="no-contents d-flex justify-content-center align-items-center">
          フォローされていません
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="item4" role="tabpanel" aria-labelledby="favorites-tab">
      <% if @user.favorites.any? %>
        <%= render 'show_favorites', favorites: @favorites %>
      <% else %>
        <div class="no-contents d-flex justify-content-center align-items-center">
          保存した投稿がありません
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= paginate @users %>
    <% end %>
  </div>
</div>